package com.rongyi.bookcase.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rongyi.bookcase.dao.BookDaoBean;

import com.rongyi.bookcase.dao.BookDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoBeanDaoConfig;

    private final BookDaoBeanDao bookDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoBeanDaoConfig = daoConfigMap.get(BookDaoBeanDao.class).clone();
        bookDaoBeanDaoConfig.initIdentityScope(type);

        bookDaoBeanDao = new BookDaoBeanDao(bookDaoBeanDaoConfig, this);

        registerDao(BookDaoBean.class, bookDaoBeanDao);
    }
    
    public void clear() {
        bookDaoBeanDaoConfig.clearIdentityScope();
    }

    public BookDaoBeanDao getBookDaoBeanDao() {
        return bookDaoBeanDao;
    }

}
